Bug Fix
justiceo/flow pull request #7
Opened 2024-11-01 11:51 UTC by Neche-Stephen

Fixed bugs on removing unnecessary libraries, removing mock tests, and optimizing process meta function.

2024-11-01 16:01 UTC, justiceo requested changes

2024-11-01 16:01 UTC, justiceo commented on src/chatgpt-log.ts
> +      userId: uuidv4(),
The caller would provide this param. Let's leave it empty for now and also remove the uuid package.

2024-11-01 16:01 UTC, justiceo commented on src/chatgpt-log.ts
> +      operatingSystem: `${os.type()} ${os.release()}`,
Update to use the format "os.platform()/os.release()", os.platform() is much more precise than type()

2024-11-01 16:01 UTC, justiceo commented on spec/chatgpt.spec.ts
> +import { start } from "repl";
I don't see where `start` is used in this file. Also the repl package referenced here is not a declared dependency in package.json.

Remove from here and other places.

2024-11-01 16:01 UTC, justiceo commented on src/chatgpt-log.ts
>  import { start } from "repl";
Update your imports, here and elsewhere to follow the order

 1. system packages e.g. "os", "path"
 2. 3rd party libraries e.g. "node-machine-id"
 3. local dependencies e.g. "./log-entry"

2024-11-01 16:01 UTC, justiceo commented on spec/chatgpt.spec.ts
> +    model: "gpt-4o",
Update to use gpt-4o-mini

2024-11-02 02:03 UTC, justiceo requested changes

2024-11-02 02:03 UTC, justiceo commented on src/chatgpt-log.ts
> +      operatingSystem: `${os.platform()} ${os.release()}`,
"/" for consistency

2024-11-02 02:03 UTC, justiceo commented on spec/chatgpt.spec.ts
> +// System packages
Keep it in mind, no need to put it in the code :)

2024-11-02 02:47 UTC, Neche-Stephen commented on spec/chatgpt.spec.ts
> +// System packages
Oh dear. I forgot to remove that. lol

2024-11-15 19:19 UTC, justiceo approved these changes
See comments

2024-11-15 19:19 UTC, justiceo commented on spec/gemini.spec.ts
> +    model: "models/gemini-1.5-pro",
Use flash

2024-11-15 19:19 UTC, justiceo commented on data/2024-11-01.jsonl
Both jsonl files look outdated based on current implementation.

2024-11-15 19:19 UTC, merged

2024-11-15 21:44 UTC, Neche-Stephen commented on data/2024-11-01.jsonl
Yea, the PR has been around for a long time. Subsequent PRS will have more recent entries